name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
permissions: {}

jobs:
  super-lint:
    permissions: { contents: read, packages: read, statuses: write }
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with: { egress-policy: audit }
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { persist-credentials: false }
      - uses: super-linter/super-linter/slim@61abc07d755095a68f4987d1c2c3d1d64408f1f9 # v8.5.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          USE_FIND_ALGORITHM: true # support detached-head checkouts
          VALIDATE_GIT_COMMITLINT: false # commitlint is bad
