name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
permissions: {}

jobs:
  super-lint:
    permissions: { contents: read, packages: read, statuses: write }
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with: { egress-policy: audit }
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { persist-credentials: false }
      - uses: super-linter/super-linter/slim@61abc07d755095a68f4987d1c2c3d1d64408f1f9 # v8.5.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          USE_FIND_ALGORITHM: true # support detached-head checkouts
          VALIDATE_GIT_COMMITLINT: false # commitlint is bad
